INSERT INTO dog(dog_name, breed, origin) VALUES ('Cherry', 'Golden Retriever', 'Asia');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Buddy', 'Labrador', 'South America');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Max', 'German Shepherd', 'North America');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Rocky', 'Cane Corso', 'Europe');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Bailey', 'Chow Chow', 'Asia');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Charlie', 'French Bulldog', 'Europe');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Cooper', 'Australian Shepherd', 'Oceania');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Bear', 'Newfoundland', 'North America');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Hachi', 'Shiba Inu', 'Asia');
INSERT INTO dog(dog_name, breed, origin) VALUES ('Winston', 'Bulldog', 'Europe');
